basePath: /
definitions:
  dto.Base:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: https://none.run.app
info:
  contact:
    email: suport@none.me
    name: None
  description: Return Image Bucket.
  license:
    name: 'Idp: v0.0.1'
    url: none.me
  termsOfService: None
  title: Test Image Endpoint's
  version: 0.0.1
paths:
  /imgs/get:
    get:
      consumes:
      - application/json
      description: Retrieves the URL of an object from the Google Cloud Storage.
      parameters:
      - description: Bucket
        in: body
        name: bucket
        required: true
        schema:
          type: string
      - description: File
        in: body
        name: file
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Base'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Base'
      summary: Get object URL from Google Cloud Storage
      tags:
      - Cloud Storage
swagger: "2.0"
